### ISSUE TITLE
Broken links?

### ISSUE THREAD

**Issue by jieverson** [webpro/awesome-dotfiles#16]
Pull requests are not been aproved by Travis. 

#17.1 failed

Issues :-(

> Links 
  1. [L017] 301 http://code.tutsplus.com/tutorials/setting-up-a-mac-dev-machine-from-zero-to-hero-with-dotfiles-part-2--cms-23145  → https://code.tutsplus.com/tutorials/setting-up-a-mac-dev-machine-from-zero-to-hero-with-dotfiles-part-2--cms-23145 
  2. [L017] 301 http://code.tutsplus.com/tutorials/setting-up-a-mac-dev-machine-from-zero-to-hero-with-dotfiles--net-35449  → https://code.tutsplus.com/tutorials/setting-up-a-mac-dev-machine-from-zero-to-hero-with-dotfiles--net-35449 
  3. [L088] 301 http://freshshell.com/  → https://freshshell.com/ 
  4. [L108] 301 https://github.com/kevinSuttle/OSXDefaults  → https://github.com/kevinSuttle/macOS-Defaults 

I tested the links, but they are actually working. :s

**Comment by webpro** [comment]
Thanks @jieverson, I've just updated all links.
