### ISSUE TITLE
XDG paths

### ISSUE THREAD

**Issue by z0rc** [webpro/awesome-dotfiles#33]
Probably this guide should at least mention the [XDG Base Dir Spec](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html).

It's sad to see $HOME's cluttered with dotfiles, while everything related to configuration can, and most likely should be placed into $XDG_CONFIG_HOME.

Arch wiki has a very good overview of general XDG base dir support at https://wiki.archlinux.org/index.php/XDG_Base_Directory_support, so this can be a good pointer on how to organize your own dotfiles.

**Comment by webpro** [comment]
Thanks, @z0rc! I've added the links.
