### ISSUE TITLE
Add dots

### ISSUE THREAD

**Issue by Addvilz** [webpro/awesome-dotfiles#51]
Hey @webpro 

I made this - https://github.com/Addvilz/dots - do you think it could be useful to add this to the list? I think it's a good example on how to automate both installation and maintenance of a dev / mixed purpose workstation.

**Comment by jtagcat** [comment]
Pro tip: make a MR for it.

**Comment by Addvilz** [comment]
@jtagcat I will, if @webpro confirms he wants it listed. I will not waste my or his time making a PR that I am unsure if he will approve of.

**Comment by webpro** [comment]
Thanks @Addvilz! I even added a new Ansible section, as it still seems to be a popular choice for automation, right? If you have more ideas or know good ansible repos, please let me know.

**Comment by Addvilz** [comment]
@webpro thanks! Yes, Ansible is quite popular, I'd go as far as to say that to date it is probably the most popular one, of all the configuration management and automation systems out there.

> If you have more ideas or know good ansible repos, please let me know.

Will do, thanks!
