### ISSUE TITLE
Add a collaborative `$HOME` cleaning tool:  xdg-ninja

### ISSUE THREAD

**Issue by tkapias** [webpro/awesome-dotfiles#67]
I would like to suggest this tool for people triying to clean their home directory from dotfiles and other unwanted directories manually:

[xdg-ninja](https://github.com/b3nj5m1n/xdg-ninja)

It's a tool which analyze your `$HOME` and generate a user currated list of advices and solutions to clean the mess.

Really helpful when you don't know where to start.

**Comment by webpro** [comment]
Oh I like this, thanks for the suggestion! Could you please open a PR?
